import type { CodegenConfig } from "@graphql-codegen/cli";

/**
 * client-preset codegen (#67/#36). Reads the committed `apps/api/schema.graphql`
 * by relative path over a Turbo task edge (`@wear/web#codegen` dependsOn
 * `@wear/api#schema`) — never a live `${BACKEND_URL}` — so a fresh clone
 * typechecks with no running server or DB. Output (`src/gql/`) is gitignored and
 * regenerated by the `codegen` task; `typecheck`/`build` depend on it.
 *
 * The migration authors documents as `graphql()` calls: the walking skeleton's
 * lone document under `src/app/**`, and the migrated page slices' central
 * documents under `src/graphql/{queries,mutations}/**` (#36 story 21). The
 * unmigrated Pages Router (admin) still imports its `gql` documents from the same
 * `src/graphql/**` tree; those were authored against the *old* backend and would
 * fail validation against the committed schema. `pluckConfig` restricts document
 * extraction to the `graphql` tag so those legacy `gql` documents are ignored —
 * only the migrated `graphql()` documents are generated, and each operation is
 * defined exactly once for the client preset.
 */
const config: CodegenConfig = {
	schema: "../api/schema.graphql",
	documents: ["src/app/**/*.{ts,tsx}", "src/graphql/**/*.ts"],
	// The tree has no `graphql()` documents until the first one is authored;
	// don't fail the task on an empty scan.
	ignoreNoDocuments: true,
	// Only extract the `graphql()` tag — leave the frozen `gql` documents that
	// still feed the unmigrated Pages Router (and its committed
	// `src/generated/types.ts`) out of this schema's validation.
	pluckConfig: {
		globalGqlIdentifierName: ["graphql"],
	},
	generates: {
		"src/gql/": {
			preset: "client",
			presetConfig: {
				// Zero fragments exist; masking would only add ceremony (#36).
				fragmentMasking: false,
			},
			config: {
				// Honest scalars: no silent `any`. DateTime is an ISO string over the
				// wire, formatted at render.
				strictScalars: true,
				scalars: { DateTime: "string" },
				// Load-bearing under verbatimModuleSyntax (#26); the enum-value naming
				// transform is dropped — Pothos declares values explicitly.
				enumsAsTypes: true,
			},
		},
	},
};

export default config;
