import type { CodegenConfig } from "@graphql-codegen/cli";

/**
 * client-preset codegen (#67/#36). Reads the committed `apps/api/schema.graphql`
 * by relative path over a Turbo task edge (`@wear/web#codegen` dependsOn
 * `@wear/api#schema`) — never a live `${BACKEND_URL}` — so a fresh clone
 * typechecks with no running server or DB. Output (`src/gql/`) is gitignored and
 * regenerated by the `codegen` task; `typecheck`/`build` depend on it.
 *
 * During the migration only the App Router tree (`src/app/**`) uses the generated
 * `graphql()` documents. The 18 legacy `gql` documents under `src/graphql/**`
 * stay frozen, feeding the old `typescript-react-apollo` codegen (`codegen.yml`)
 * for the unmigrated Pages Router; later slices move them here page by page.
 */
const config: CodegenConfig = {
	schema: "../api/schema.graphql",
	documents: ["src/app/**/*.{ts,tsx}"],
	// The tree has no `graphql()` documents until the first one is authored;
	// don't fail the task on an empty scan.
	ignoreNoDocuments: true,
	generates: {
		"src/gql/": {
			preset: "client",
			presetConfig: {
				// Zero fragments exist; masking would only add ceremony (#36).
				fragmentMasking: false,
			},
			config: {
				// Honest scalars: no silent `any`. DateTime is an ISO string over the
				// wire, formatted at render.
				strictScalars: true,
				scalars: { DateTime: "string" },
				// Load-bearing under verbatimModuleSyntax (#26); the enum-value naming
				// transform is dropped — Pothos declares values explicitly.
				enumsAsTypes: true,
			},
		},
	},
};

export default config;
