type Address {
  addressLine1: String
  addressLine2: String
  city: String
  country: String
  id: ID!
  zipCode: String
}

enum Category {
  BLAZER
  BLOUSE
  DRESS
  JACKET
  SHIRT
  SWEATSHIRT
  TROUSERS
  TSHIRT
}

input ChangePasswordInput {
  password: String!
  token: String!
}

input CreateItemInput {
  category: Category!
  description: String
  gender: Gender!
  imageUrl: String!
  name: String!
  price: Float!
  sizes: [ItemSizesInput!]
}

input CreateOrderInput {
  itemId: ID!
  size: SizeSymbol!
}

scalar DateTime

input EditItemInput {
  category: Category
  id: String!
  imageUrl: String
  name: String
  price: Float
  sizes: [ItemSizesInput!]
}

enum Gender {
  MAN
  WOMAN
}

type Item {
  category: Category!
  createdAt: DateTime!
  createdBy: User
  description: String
  gender: Gender!
  id: ID!
  imageUrl: String!
  name: String!
  price: Float!
  sizes: [Size!]
  updatedAt: DateTime!
}

input ItemSizesInput {
  quantity: Int!
  sizeSymbol: SizeSymbol!
}

type ItemsAndCount {
  count: Int!
  maxPrice: Float
  select: [Item!]
}

input LoginInput {
  email: String!
  password: String!
}

type Mutation {
  changePassword(input: ChangePasswordInput!): SuccessMessage!
  changeUserRole(email: String!, role: UserRole!): SuccessMessage!
  createItem(input: CreateItemInput!): Item!
  createOrder(input: [CreateOrderInput!]!): Order!
  deleteAccount(password: String!): SuccessMessage!
  deleteItem(id: ID!): SuccessMessage!
  deleteOrder(id: ID!): SuccessMessage!
  login(input: LoginInput!): User!
  manageOrder(id: ID!, status: OrderStatus!): SuccessMessage!
  register(input: RegisterInput!): User!
  resetPassword(input: ResetPasswordInput!): SuccessMessage!
  signout: SuccessMessage!
  subscribeToNewsletter(newsletter: Boolean!): SuccessMessage!
  updateAddress(input: UpdateAddressInput!): SuccessMessage!
  updateItem(input: EditItemInput!): Item!
  updatePersonalInfo(input: PersonalInfoInput!): SuccessMessage!
}

type Order {
  createdAt: DateTime!
  id: ID!
  orderedBy: User
  orderedItems: [Ordered_Item!]
  status: OrderStatus!
  updatedAt: DateTime!
}

enum OrderStatus {
  COMPLETED
  PAID
  PENDING
  SENT
}

type Ordered_Item {
  id: ID!
  item: Item
  sizeSymbol: SizeSymbol!
}

input PersonalInfoInput {
  firstName: String
  lastName: String
  phoneNumber: String
}

type Query {
  item(id: ID!): Item
  items(where: SearchItemInput): ItemsAndCount!
  me: User
  order(id: ID!): Order
  orders(where: SearchOrdersInput): [Order!]
  user(id: ID!): User
  userOrders(skip: Int, take: Int): UserOrdersAndCount!
  users(where: SearchUserInput): UsersAndCount!
}

input RegisterInput {
  email: String!
  password: String!
}

input ResetPasswordInput {
  email: String!
}

input SearchItemInput {
  available: Boolean
  category: Category
  gender: Gender
  id: ID
  name: String
  priceFrom: Float
  priceTo: Float
  skip: Int
  sortBy: String
  sortOrder: SortOrder
  take: Int
}

input SearchOrdersInput {
  id: ID
  skip: Int
  sortBy: String
  sortOrder: SortOrder
  status: OrderStatus
  take: Int
}

input SearchUserInput {
  email: String
  firstName: String
  lastName: String
  role: UserRole
  skip: Int
  take: Int
}

type Size {
  quantity: Int!
  sizeSymbol: SizeSymbol!
}

enum SizeSymbol {
  L
  M
  S
  XL
  XS
  XXL
}

enum SortOrder {
  ASC
  DESC
}

type SuccessMessage {
  message: String!
}

input UpdateAddressInput {
  addressLine1: String
  addressLine2: String
  city: String
  country: String
  zipCode: String
}

type User {
  address: Address
  createdAt: DateTime!
  email: String!
  firstName: String
  id: ID!
  lastName: String
  newsletter: Boolean!
  phoneNumber: String
  role: UserRole!
  updatedAt: DateTime!
}

type UserOrdersAndCount {
  count: Int!
  select: [Order!]
}

enum UserRole {
  ADMIN
  CUSTOMER
  EMPLOYEE
}

type UsersAndCount {
  count: Int!
  select: [User!]!
}
