scalar DateTime

input LoginInput {
  email: String!
  password: String!
}

type Mutation {
  login(input: LoginInput!): User!
  register(input: RegisterInput!): User!
  signout: SuccessMessage!
}

type Query {
  me: User
}

input RegisterInput {
  email: String!
  password: String!
}

type SuccessMessage {
  message: String!
}

type User {
  createdAt: DateTime!
  email: String!
  firstName: String
  id: ID!
  lastName: String
  phoneNumber: String
  role: UserRole!
  updatedAt: DateTime!
}

enum UserRole {
  ADMIN
  CUSTOMER
  EMPLOYEE
}
